#!/bin/bash
# Liste des fichiers
files=(
    "0-hello_world"
    "1-confused_smiley"
    "2-hellofile"
    "3-twofiles"
    "4-lastlines"
    "10-no_more_js"
    "11-directories"
    "12-newest_files"
    "13-unique"
    "14-findthatword"
    "15-countthatword"
    "16-whatsnext"
    "17-hidethisword"
    "18-letteronly"
    "19-AZ"
    "20-hiago"
    "21-reverse"
    "22-users_and_homes"
    "5-firstlines"
    "6-third_line"
    "7-file"
    "9-duplicate_last_line"
)
# Ajout du shebang et mise à jour des permissions
for file in "${files[@]}"; do
    echo '#!/bin/bash' | cat - "$file" > temp && mv temp "$file"
    chmod u+x "$file"
done
