#!/bin/bash
# Liste des fichiers
files=(
    "0-alias"
    "1-hello_you"
    "2-path"
    "3-paths"
    "4-global_variables"
    "10-love_exponent_breath"
    "11-binary_exponent_breath"
    "12-combinations"
    "13-print_float"
    "14-decimal_to_hexadecimal"
    "5-local_variables"
    "6-create_local_variables"
    "7-create_global_variable"
    "8-true_knowledge"
    "9-divide_and_rule"
)
# Ajout du shebang et mise à jour des permissions
for file in "${files[@]}"; do
    echo '#!/bin/bash' | cat - "$file" > temp && mv temp "$file"
    chmod u+x "$file"
done
